import Head from "next/head";
import Footer from "../../components/Footer";
import Main from "../../components/Main";
import Nav2 from "../../components/Nav2";

export default function More() {
    return (<>
        <Head>
            <title>Pandêmico</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="assets/pandemic.png" />
        </Head>
        <Nav2 />
        
        <Footer />
    </>
    )
}