import Head from "next/head";
import Footer from "../../components/Footer";
import Main from "../../components/Main";
import Nav from "../../components/Nav";

export default function Animes() {
    return (
        <>
            <Head>
                <title>Pandêmico</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="assets/pandemic.png" />
            </Head>
            <Nav />
            <Main text={`Zuo Tianchen é o último humano vivo em uma cidade infestada de zumbis. Quando ele estava prestes a morrer ele acabou voltando para o seu eu de 10 anos atrás. Qual será o desfecho desta vez com Zuo Tianchen possuindo sua experiência de 10 anos no futuro?!!

            Ao terminar de ler um mangá que gostamos muito, sempre vem aquela dúvida sobre o que ler em seguida. Aqui deixarei nossa lista de mangás para ler após terminar essa linda obra de arte. Espero que essa lista de mangás parecidos te ajude na procura pelo que ler.

            Caso queira aprender a desenhar seus próprios personagens de anime e mangá, confira o Método Fan Art 3.0 clicando na imagem abaixo. Por um preço super acessível, a professora Mayara vai te ensinar o método que já fez milhares de pessoas aprenderem a desenhar partindo do zero.`} img={"/assets/theLastHuman.jpg"} text2={"Após o surto de infecção cerebral por Cordyceps , os civis que viviam em Seattle foram colocados sob o controle militar da FEDRA e dos Estados Unidos dentro da zona de quarentena . Com o tempo, a raiva e o ressentimento cresceram contra a FEDRA e o domínio militar sobre a cidade. Emma e Jason Patterson foram dois dos inúmeros residentes enfurecidos pelas expulsões, escassez de alimentos e execuções que os militares conduziram sob o comando do tenente Torres e do sargento. Regra de Ward . Em meados da década de 2020, os Pattersons formaram o WLF, apelidado de LOBOS, para lutar por melhores condições de vida para os civis da zona. Eles recrutaram várias pessoas para seu grupo, incluindo Alison Cole , Isaac Dixon , Hugo Gonzalez , Luis Sanchez e Marcus Wilson . No entanto, seus protestos rapidamente se transformaram em uma campanha anti-FEDRA, com os Pattersons e seu pequeno grupo de membros distribuindo propaganda anti-FEDRA, roubando suprimentos militares e incitando a sedição entre os residentes de Seattle. Suas ações levaram Ward a marcá-los como terroristas procurados.Eventualmente, os Pattersons foram eliminados pelos militares, junto com vários outros altos funcionários dos Lobos, deixando Isaac como o último líder remanescente da rebelião.  Em retaliação por suas mortes, Isaac matou três soldados FEDRA. Enquanto vários cidadãos eram moralmente contra as ações de Isaac, os membros restantes do WLF o elegeram como seu novo líder. Nas semanas seguintes, o WLF cometeu ataques a postos de controle militares, assaltou comboios e se envolveu em um conflito armado aberto contra os militares.Para combater a crescente agressão do WLF, Torres ordenou que os soldados abrissem fogo contra todo e qualquer protesto do WLF, incluindo os pacíficos. A ordem levou ao massacre do mercado de quinta-feira, um evento que viu a resposta brutal dos militares à marcha do WLF causar um aumento no apoio ao WLF e na adesão entre os residentes de Seattle. A ação foi particularmente polêmica, pois os manifestantes faziam campanha por comida para suas famílias e encerraram a campanha de propaganda militar para enquadrar o WLF como um grupo terrorista cheio de assassinos; o WLF agora se tornou conhecido como os combatentes da liberdade dos próprios cidadãos.  O aumento de membros levou a um sucesso crescente para o WLF, até mesmo soldados da FEDRA desertaram para se juntar ao grupo de milícia."} img2={"assets/wlf.png"} />
            <Footer />
        </>
    )
}