import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from 'react'
import Nav from '../components/Nav'
import Footer from '../components/Footer'
import Main from '../components/Main'

export default function Home() {
  return (
    <>
      <Head>
        <title>Pandêmico</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pandemic.svg" />
      </Head>
      <main className={styles.main}>
          <Nav />
          <Main/>
          <Footer/>
      </main>
    </>
  )
}
