import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from 'react'
import Home1 from '../components/Home'
import * as S from "./styles"

export default function Home() {
  return (
    <>
      <Head>
        <title>Pandêmico</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pandemic.svg" />
      </Head>
      <main className={styles.main}>
        <S.container>
          <Home1 />
        </S.container>
      </main>
    </>
  )
}
