import Head from "next/head";
import Footer from "../../components/Footer";
import Main from "../../components/Main";
import Nav from "../../components/Nav";

export default function Movies() {

    return (
        <>
            <Head>
                <title>Pandêmico</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="assets/pandemic.png" />
            </Head>
            <Nav />
            <Main text={`Um vírus indutor de agressão altamente contagioso chamado "Rage" é liberado na Grã-Bretanha depois que um chimpanzé infectado é libertado de um laboratório em Cambridge por um grupo de ativistas de libertação animal . Ela se espalha rapidamente e se torna uma epidemia , resultando em colapso social . 28 dias após o surto inicial, o entregador de bicicletas Jim acorda do coma no Hospital St Thomas, em Londres, que foi abandonado com sinais de catástrofe. Jim é atacado por humanos infectados, mas resgatado pelos sobreviventes Selena e Mark. A pedido de Jim, o grupo viaja para a casa de seus pais em Deptford ., onde ele descobre que eles cometeram suicídio. Naquela noite, Mark recebe um corte no braço que é atingido por sangue infectado durante um ataque, levando Selena a matá-lo antes que ele se transforme. \n

            Jim e Selena encontram o motorista de táxi Frank e sua filha Hannah na Balfron Tower , de quem ficam sabendo de uma transmissão militar oferecendo proteção em um bloqueio em Manchester . Com os suprimentos diminuindo, Frank pede a Jim e Selena que acompanhem ele e Hannah ao bloqueio, que eles aceitam. O grupo segue para Manchester no táxi de Frank, mas ao chegar encontram o bloqueio deserto. Enquanto o grupo luta para planejar seu próximo movimento, Frank é infectado quando uma gota de sangue cai em seu olho. Os soldados chegam logo depois e matam Frank a tiros. \n

            Os sobreviventes restantes são levados para uma mansão fortificada sob o comando do Major Henry West. No entanto, a segurança prometida pelos soldados acaba sendo um estratagema quando West revela a Jim que a transmissão pretendia atrair mulheres sobreviventes à escravidão sexual para repovoar o mundo. Os soldados tentam matar Jim depois que ele se recusa a ser cúmplice de seu plano, mas Jim escapa. Depois de atrair West para longe da mansão, Jim libera Private Mailer, um soldado infectado mantido acorrentado para observação, resultando na morte dos homens de West. Jim, Selena e Hannah tentam sair no táxi de Frank, mas West se esgueirou para o banco de trás e atirou em Jim. Hannah retalia colocando o táxi em marcha à ré, permitindo que Mailer puxe West pela janela traseira e o mate, enquanto os três sobreviventes vão embora.\n

            Outros 28 dias depois, Jim se recupera em uma cabana remota em Cumbria , onde os infectados são mostrados morrendo de fome. Enquanto um caça finlandês sobrevoa, Jim, Selena e Hannah abrem uma enorme faixa de tecido com a palavra "HELLO". Os três sobreviventes observam o jato com otimismo enquanto o piloto os avista. \n`} img={"/assets/28days.jpg"} text2={"Em resumo, a história se inicia com os irmãos Johnny e Bárbara indo visitar o túmulo de seu pai em uma zona rural erma, chegando ao local eles são atacados por um estranho esfarrapado e ensandecido. Johnny morre na tentativa de proteger Bárbara e ela foge em desespero, indo se abrigar em uma casa de fazenda onde encontra Ben, um homem que deixa evidências claras de que existe uma turba insana e perigosa de pessoas causando violência e tumulto nas cidades e se acercando da propriedade rural onde os dois se entocam. A turba é obviamente composta por zumbis, cadáveres reanimados por uma força epidêmica cuja origem é apenas insinuada ao longo do livro. Sem muitas alternativas, Ben e Bárbara são forçados a lutar pela sobrevivência, recebendo uma confusa e nem sempre bem vinda ajuda de outros sobreviventes que se refugiam na casa de fazenda.O primeiro ponto alto a ser citado sobre a obra de Russo é que a trama fica ainda mais instigante e clara na literatura. As nuances de crítica social, as características dos personagens e a tensão instaurada no ambiente desesperador causam no leitor uma sensação de inquietude muito grande. O autor soube trabalhar a versão literária de A Noite dos Mortos-Vivos de maneira ímpar, o terror, o horror e a repugnância são características fortes que, aliadas a ambientação e a tensão entre os personagens, causam pavor e ansiedade legítimos. Portanto, a versão literária de A Noite dos Mortos-Vivos não deve ser relegada como um simples produto caça-níquel, pois ela acrescenta uma experiência totalmente nova a essa verdadeira história clássica."} img2={"assets/night.jpg"} />
            <Footer />
        </>
    )
}